In [1]:
import numpy as np

In [6]:
# Criando array
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [7]:
# Criando array com tipo específico
mtfloat = np.array([1,2,3], dtype=np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype=np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# Mudando o tipo de array
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
# Realizando conversão
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [8]:
# Inverso
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [10]:
# Multidimensional
mt7 = np.array([[7,2,23], [12,27,4], [5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [13]:
# Arrays vazios tipificados
vazio = np.empty([3,2], dtype=int)
print(vazio)
print('\n')
# Matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print('\n')
# Valores 1
um = np.ones([5,7])
print(um)
print('\n')
# Matriz quadrada com diagonal de valores 1 e resto zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# Valores aleatórios entre 0 e 1
ale = np.random.random((5))
print(ale)
print('\n')
# Valores aleatórios distrib. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print('\n')
# Val aleatórios 3x4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.24196822 0.23407999 0.01623045 0.45922593 0.90211555]


[-0.18592483  1.11423648  0.26975556 -1.20602967 -0.40675305]


[[9.61212828 9.33207823 2.25043643 6.59296055]
 [4.79885362 6.02851968 0.52015195 1.98851495]
 [6.45064002 9.90977653 1.40125389 9.84194498]]


In [16]:
# Outros métodos de aleatoriedade
# Semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)
print('\n')

# Gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]


[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [20]:
# Unique method
j = np.array([11,12,13,14,15,16,17,12,13,11,18,19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [21]:
# Funções específicas
# Cria matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
print(k)
# Posição especcífica da matriz
print(k[0][1])
# Medidas de tamanho
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [22]:
# Funções matemáticas
# Máx, mín, soma, média, desvio padrão
print(k.max())
print(k.min())
print(k.sum())
print(k.mean())
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [26]:
# Funções universais, aplicadas a todos os elementos
k1 = np.array([1,4,9,16,25,36])
# Raiz quadrada e elementos ao quadrado
print(np.sqrt(k1))
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [28]:
# Extração de elementos
m = np.array([1,2,3,4,5,6])
print(m[1])
print(m[0:2])
print(m[1:])
print(m[-3:])

2
[1 2]
[2 3 4 5 6]
[4 5 6]


In [29]:
# Extração de linhas e colunas
l = np.array([[3,5],[6,1],[7,4]])
l_linha_1 = l[0,:]
l_linha_2 = l[1,:]
l_coluna_1 = l[:,0]
l_coluna_2 = l[:,1]
print(l_linha_1)
print(l_linha_2)
print(l_coluna_1)
print(l_coluna_2)

[3 5]
[6 1]
[3 6 7]
[5 1 4]


In [31]:
# Adição e multiplicação de matrizes
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])
res1 = n+o
print(res1)
print('\n')
res2 = n*o
print(res2)
print('\n')
p = np.array([[1,2],[3,4],[5,6]])
q = np.array([2,1])
print(p+q)

[[2 3]
 [4 5]]


[[1 2]
 [3 4]]




[[3 3]
 [5 5]
 [7 7]]


In [38]:
# Transposição, rearranja um conjunto de 15 elementos de 0 a 14
f = np.arange(15).reshape((3,5))
print(f)
s= f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [40]:
# Outra maneira de tanspôr
r = np.arange(15).reshape((3,5))
print(r)
print('\n')
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [45]:
# Expressões lógicas
# Where
v = np.random.randn(4,4)
print(v)
# Criz matriz com valores baseados na condição
x = (v > 0)
print(x)
# Escolhendo os valores da matriz
z = np.where(x > 0, 1, -1)
print(z)

[[ 0.99178062 -0.8393003  -1.3569201  -1.19808444]
 [-0.81966133 -1.32835943 -0.1764679   1.12846389]
 [ 0.26715514 -1.79780975 -1.10028246 -1.33206642]
 [ 0.26629441  0.13990983 -0.99613425  1.30999949]]
[[ True False False False]
 [False False False  True]
 [ True False False False]
 [ True  True False  True]]
[[ 1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1 -1 -1]
 [ 1  1 -1  1]]
